# Docker Compose configuration for Job Application Management System

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: job_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobapp_db
      POSTGRES_USER: jobapp_user
      POSTGRES_PASSWORD: jobapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobapp_user -d jobapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: job_app_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://jobapp_user:jobapp_password@database:5432/jobapp_db
      SECRET_KEY: your-secret-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "5000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./app/backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: job_app_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  postgres_data:

networks:
  default:
    name: job_app_network